name: 👷

on:
  push:
    branches: [master, main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          DESTINATION_BRANCH: ${{secrets.BRANCH}}
          KEYWORD: ${{secrets.KEYWORD}}
